# OrangePi 3B
base_img: https://drive.google.com/file/d/1btJGKqBKsRXCr4q_UDm4ZntCL4Vv_xeS/view?usp=drive_link
base_img_can_download: false
base_img_name: Orangepi3b_1.0.4_debian_bookworm_server_linux5.10.160.7z
base_img_sha256: d56a378f8fb5267d1ff18c5dd4a974edf33653555943c9bcee80f8a8dcd3b0f8
expand_mb: 3072
partitions:             # IN ORDER THEY SHOULD BE MOUNTED partnumber: mountpath
  2: /
  1: /boot/
components:             # IN THE ORDER THEY SHOULD BE RUN
  - suppress_initramfs_stuff
  - update_system
  - opi3b_usersetup
  - opi3b_hwconfig
  - core_system_config
  - lastboot_scripts
  - readonly
  - opi3b_readonly
  - install_software
  - opi3b_install_software
  - arpirobot_config
  - network_config
  - network_config_ethernet
  - opi3b_network_config_ethernet # Fix ethernet interface name
  - end_suppress_initramfs_stuff
  - cleanup