# OrangePi 3B
#   v1.1.1 Tested (note: 1.1.1 uses 2.1 pinout not 1.1 pinout)
#   v2.1 board changed Wireless module, physical board size, and more.
#   The base image used (1.0.6 vendor image) *should* support both v2.1 and v1.1.1
# Original vendor link: https://drive.google.com/file/d/1sqeY04gz3WkOkO-dV18nec0qNROoH_eL/view?usp=drive_link
# OrangePi sometimes deletes old images though, so using a copy on github release instead
base_img: https://github.com/ArPiRobot/ArPiRobot-ImageScripts/releases/download/baseimgs/Orangepi3b_1.0.6_debian_bookworm_server_linux5.10.160.7z
base_img_can_download: true
base_img_name: Orangepi3b_1.0.6_debian_bookworm_server_linux5.10.160.7z
base_img_sha256: e82d3194411c224777ba532da446bc264fd5dcea6d8463cfb5983acb0a3b5dd8
expand_mb: 3072
partitions:             # IN ORDER THEY SHOULD BE MOUNTED partnumber: mountpath
  2: /
  1: /boot/
components:             # IN THE ORDER THEY SHOULD BE RUN
  - suppress_initramfs_stuff
  - opi3b_repofix
  - update_system
  - opi3b_usersetup
  - opi3b_hwconfig
  - core_system_config
  - lastboot_scripts
  - readonly
  - opi3b_readonly
  - install_software
  - opi3b_install_software
  - arpirobot_config
  - network_config
  - network_config_ethernet
  - opi3b_network_fixes
  - end_suppress_initramfs_stuff
  - cleanup