# OrangePi Zero 2W 1GB/2GB/4GB (1.5GB NOT SUPPORTED AS THIS REQUIRES A DIFFERENT BASE IMAGE!!!)
base_img: https://drive.google.com/file/d/1rIqFzTh89p0WrpfRYNkyk-63r99ITmfr/view?usp=drive_link
base_img_can_download: false
base_img_name: Orangepizero2w_1.0.0_debian_bookworm_server_linux6.1.31.7z
base_img_sha256: 2a9b3459dd306e1518bae1956ebc47113b9be24b37f12b217549b7178b7a5a8f
expand_mb: 3072
partitions:             # IN ORDER THEY SHOULD BE MOUNTED partnumber: mountpath
  1: /
components:             # IN THE ORDER THEY SHOULD BE RUN
  - suppress_initramfs_stuff
  - opizero2w_repofix
  - update_system
  - opizero2w_usersetup
  - opizero2w_hwconfig
  - core_system_config
  - lastboot_scripts
  - readonly
  - opizero2w_readonly
  - install_software
  - opizero2w_install_software
  - arpirobot_config
  - network_config
  - opizero2w_network_fixes
  - end_suppress_initramfs_stuff
  - cleanup