# OrangePi Zero 2W
# Tested on v1.1.1 board (likely same as v1.1)
# Original vendor link: https://drive.google.com/file/d/134rjGe6QZfiuR3i00wPl9bBoiwlZdseH/view?usp=drive_link
# OrangePi sometimes deletes old images though, so using a copy on github release instead
base_img: https://github.com/ArPiRobot/ArPiRobot-ImageScripts/releases/download/baseimgs/Orangepizero2w_1.0.2_debian_bookworm_server_linux6.1.31.7z
base_img_can_download: true
base_img_name: Orangepizero2w_1.0.2_debian_bookworm_server_linux6.1.31.7z
base_img_sha256: 949fb0b86dfe231cabcb87325d4a6bc827e77ac562ae32c7a51070ac9975ba1e
expand_mb: 3072
partitions:             # IN ORDER THEY SHOULD BE MOUNTED partnumber: mountpath
  1: /
components:             # IN THE ORDER THEY SHOULD BE RUN
  - suppress_initramfs_stuff
  - opizero2w_repofix
  - update_system
  - opizero2w_usersetup
  - opizero2w_hwconfig
  - core_system_config
  - lastboot_scripts
  - readonly
  - opizero2w_readonly
  - install_software
  - opizero2w_install_software
  - arpirobot_config
  - network_config
  - end_suppress_initramfs_stuff
  - cleanup