# All targeted Raspberry Pi boards. Uses armv6 image because Pi Zero.
base_img: https://downloads.raspberrypi.com/raspios_lite_armhf/images/raspios_lite_armhf-2024-03-15/2024-03-15-raspios-bookworm-armhf-lite.img.xz
base_img_sha256: 4fa99737265ac338a9ed0643f502246b97b928e5dfffa92939242e26e290638d
expand_mb: 3072
partitions:             # IN ORDER THEY SHOULD BE MOUNTED partnumber: mountpath
  2: /
  1: /boot/firmware
components:             # IN THE ORDER THEY SHOULD BE RUN
  - update_system
  - rpi_usersetup
  - rpi_hwconfig
  - core_system_config
  - lastboot_scripts
  - readonly
  - rpi_readonly
  - install_software
  - rpi_install_software
  - arpirobot_config
  - network_config
  - cleanup